server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: autorizacion-service
          uri: lb://autorizacion-service
          predicates:
            - Path=/autorizacion/**
        - id: calculo-service
          uri: lb://calculo-service
          predicates:
            - Path=/calculo/**
        - id: justificativos-service
          uri: lb://justificativos-service
          predicates:
            - Path=/justificativos/**
        - id: reloj-service
          uri: lb://reloj-service
          predicates:
            - Path=/reloj/**